FROM node:20-slim

WORKDIR /app

# System deps (dev)
RUN apt-get update \
  && apt-get install -y --no-install-recommends ffmpeg openssl ca-certificates wget \
  && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare pnpm@9.12.0 --activate

ENV NODE_ENV=development
ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN pnpm config set store-dir /pnpm/store

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./

COPY apps ./apps
COPY packages ./packages
COPY configs ./configs

RUN pnpm install --prod=false



CMD ["pnpm", "--filter", "worker", "start:dev"]
